export const seedUsers = [
  {
    name: 'BiteFlow Administrator',
    email: 'admin@biteflow.com',
    password: 'AdminPassword123!',
    phone: '+91 98450 99999',
    role: 'ADMIN',
    addresses: [
      {
        label: 'Office',
        fullName: 'BiteFlow Operations',
        phone: '+91 98450 99999',
        addressLine1: 'BiteFlow Central Hub, 100 Feet Road',
        addressLine2: 'HAL 2nd Stage',
        area: 'Indiranagar',
        street: '100 Feet Road, HAL 2nd Stage, Indiranagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560038',
        zipCode: '560038',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Rahul Sharma',
    email: 'user@biteflow.com',
    password: 'UserPassword123!',
    phone: '+91 98450 12345',
    role: 'USER',
    addresses: [
      {
        label: 'Home',
        fullName: 'Rahul Sharma',
        phone: '+91 98450 12345',
        addressLine1: '12, 5th Main Road',
        addressLine2: 'Sector 4',
        area: 'HSR Layout',
        street: '12, 5th Main Road, Sector 4, HSR Layout',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560102',
        zipCode: '560102',
        country: 'India',
        isDefault: true,
      },
      {
        label: 'Work',
        fullName: 'Rahul Sharma',
        phone: '+91 98450 12345',
        addressLine1: 'Tower B, 3rd Floor, Embassy TechVillage',
        addressLine2: 'Outer Ring Road',
        area: 'Bellandur',
        street: 'Tower B, 3rd Floor, Embassy TechVillage, Bellandur',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560103',
        zipCode: '560103',
        country: 'India',
        isDefault: false,
      },
    ],
  },
  {
    name: 'Priya Nair',
    email: 'priya.nair@biteflow.com',
    password: 'UserPassword123!',
    phone: '+91 98451 23456',
    role: 'USER',
    addresses: [
      {
        label: 'Home',
        fullName: 'Priya Nair',
        phone: '+91 98451 23456',
        addressLine1: '45, 4th Cross, 6th Block',
        area: 'Koramangala',
        street: '45, 4th Cross, 6th Block, Koramangala',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560034',
        zipCode: '560034',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Arjun Kumar',
    email: 'arjun.k@biteflow.com',
    password: 'UserPassword123!',
    phone: '+91 98452 34567',
    role: 'USER',
    addresses: [
      {
        label: 'Home',
        fullName: 'Arjun Kumar',
        phone: '+91 98452 34567',
        addressLine1: '88, 12th Main, HAL 2nd Stage',
        area: 'Indiranagar',
        street: '88, 12th Main, HAL 2nd Stage, Indiranagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560038',
        zipCode: '560038',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Sneha Reddy',
    email: 'sneha.reddy@biteflow.com',
    password: 'UserPassword123!',
    phone: '+91 98453 45678',
    role: 'USER',
    addresses: [
      {
        label: 'Home',
        fullName: 'Sneha Reddy',
        phone: '+91 98453 45678',
        addressLine1: 'Villa 14, Prestige Ozone',
        area: 'Whitefield',
        street: 'Villa 14, Prestige Ozone, Whitefield',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560066',
        zipCode: '560066',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Karthik Raj',
    email: 'karthik.raj@biteflow.com',
    password: 'UserPassword123!',
    phone: '+91 98454 56789',
    role: 'USER',
    addresses: [
      {
        label: 'Home',
        fullName: 'Karthik Raj',
        phone: '+91 98454 56789',
        addressLine1: '32, 9th Main Road, 4th Block',
        area: 'Jayanagar',
        street: '32, 9th Main Road, 4th Block, Jayanagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560041',
        zipCode: '560041',
        country: 'India',
        isDefault: true,
      },
    ],
  },
];

export const seedCategories = [
  {
    name: 'Biryani & Pulao',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'South Indian',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'North Indian & Mughlai',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Street Food & Chaat',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Tandoor & Starters',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Chinese & Bowls',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Desserts & Sweets',
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Filter Coffee & Beverages',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
];

export const seedRestaurants = [
  {
    name: 'Spice Hub',
    description: 'Legendary slow-cooked Hyderabadi and Ambur dum biryanis, succulent kebabs, and rich handi curries crafted with royal spices.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Biryani, North Indian, Mughlai',
    address: '12, 100 Feet Road, Indiranagar, Bengaluru, Karnataka 560038',
    rating: 4.8,
    deliveryTime: '25-35 min',
    deliveryFee: 40,
    isOpen: true,
    isActive: true,
  },
  {
    name: 'Green Leaf Café',
    description: 'Crispy golden ghee roast dosas, fluffy steamed idlis, fresh Chikmagalur filter coffee, and wholesome traditional Karnataka meals.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    cuisine: 'South Indian, Pure Veg, Healthy',
    address: '45, 27th Main Road, Sector 1, HSR Layout, Bengaluru, Karnataka 560102',
    rating: 4.9,
    deliveryTime: '20-30 min',
    deliveryFee: 35,
    isOpen: true,
    isActive: true,
  },
  {
    name: 'Urban Bites',
    description: 'Vibrant city street eats: Gobi Manchurian, spicy Schezwan noodles, loaded masala fries, and sizzling paneer kathi rolls.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Street Food, Chinese, Fast Food',
    address: '88, 5th Block, Jyoti Nivas College Road, Koramangala, Bengaluru, Karnataka 560034',
    rating: 4.7,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    isOpen: true,
    isActive: true,
  },
  {
    name: 'The Royal Table',
    description: 'Opulent North Indian culinary heritage, creamy Paneer Butter Masala, tender Murgh Makhani, and smoky char-grilled tandoori delicacies.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80',
    cuisine: 'North Indian, Mughlai, Tandoor',
    address: '104 ITPL Main Road, Prestige Shantiniketan, Whitefield, Bengaluru, Karnataka 560066',
    rating: 4.8,
    deliveryTime: '30-40 min',
    deliveryFee: 45,
    isOpen: true,
    isActive: true,
  },
  {
    name: 'South Street Kitchen',
    description: 'Heritage South Indian breakfast specialties, authentic Davanagere benne dosas, and artisanal filter brews.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    cuisine: 'South Indian, Filter Coffee, Snacks',
    address: '32, 9th Main Road, 4th Block, Jayanagar, Bengaluru, Karnataka 560041',
    rating: 4.9,
    deliveryTime: '15-25 min',
    deliveryFee: 25,
    isOpen: true,
    isActive: true,
  },
];

export const sampleFoods = [
  // 1. Spice Hub (Indiranagar)
  {
    restaurantIndex: 0,
    categoryName: 'Biryani & Pulao',
    name: 'Chicken Biryani',
    description: 'Fragrant long-grain basmati rice layered with tender marinated chicken pieces, saffron, caramelized onions, served with mirchi ka salan and raita.',
    price: 249,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
  },
  {
    restaurantIndex: 0,
    categoryName: 'Biryani & Pulao',
    name: 'Mutton Biryani',
    description: 'Slow-cooked succulent tender lamb shank cuts dum-cooked in sealed handi with royal Awadhi spices, ghee, and aromatic basmati rice.',
    price: 299,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
  },
  {
    restaurantIndex: 0,
    categoryName: 'Biryani & Pulao',
    name: 'Veg Biryani',
    description: 'Garden fresh vegetables, paneer cubes, and golden mint leaves cooked in rich dum masala with aged basmati rice.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1642821373181-696a54913e9a?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 0,
    categoryName: 'Tandoor & Starters',
    name: 'Chicken 65',
    description: 'Crispy deep-fried spicy chicken morsels tempered with fresh curry leaves, crushed red chillies, and garlic yogurt dip.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
  },
  {
    restaurantIndex: 0,
    categoryName: 'Tandoor & Starters',
    name: 'Chicken Tikka',
    description: 'Boneless chicken cubes marinated in hung curd, Kashmiri red chili, mustard oil, and roasted in clay oven to charred perfection.',
    price: 229,
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
  },

  // 2. Green Leaf Café (HSR Layout)
  {
    restaurantIndex: 1,
    categoryName: 'South Indian',
    name: 'Masala Dosa',
    description: 'Crispy golden crepe roasted in pure ghee, spread with spicy red chutney and stuffed with spiced mashed potato filling.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 1,
    categoryName: 'South Indian',
    name: 'Idli',
    description: 'Pair of melt-in-mouth steamed rice and lentil cakes, accompanied by piping hot drumstick sambar and fresh coconut chutney.',
    price: 69,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 1,
    categoryName: 'South Indian',
    name: 'Vada',
    description: 'Two golden crunchy spiced urad dal fritters with peppercorns, curry leaves, and ginger. Served with coconut & tomato chutneys.',
    price: 59,
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 1,
    categoryName: 'South Indian',
    name: 'South Indian Meals',
    description: 'Grand Karnataka thali with steamed rice, ghee, sambar, rasam, kootu, vegetable palya, papad, curd, pickle, and payasam.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 1,
    categoryName: 'Filter Coffee & Beverages',
    name: 'Filter Coffee',
    description: 'Traditional South Indian frothy decoction coffee brewed with Chikmagalur roast chicory blend and creamy frothed milk in brass davarah.',
    price: 59,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },

  // 3. Urban Bites (Koramangala)
  {
    restaurantIndex: 2,
    categoryName: 'Chinese & Bowls',
    name: 'Gobi Manchurian',
    description: 'Crispy cauliflower florets tossed in wok with garlic, ginger, spring onions, green chilies, and tangy dark soya sauce.',
    price: 159,
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 2,
    categoryName: 'Chinese & Bowls',
    name: 'Veg Fried Rice',
    description: 'Wok-tossed basmati rice with finely shredded carrots, cabbage, capsicum, and beans in aromatic garlic oil.',
    price: 169,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 2,
    categoryName: 'Chinese & Bowls',
    name: 'Chicken Fried Rice',
    description: 'Smoky high-flame wok rice tossed with diced tender chicken, scrambled farm egg, spring onions, and light soya seasoning.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
  },
  {
    restaurantIndex: 2,
    categoryName: 'Street Food & Chaat',
    name: 'Masala Fries',
    description: 'Crisp golden potato fries dusted generously with zesty peri-peri chaat masala, served with mint mayo dip.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 2,
    categoryName: 'Filter Coffee & Beverages',
    name: 'Fresh Lime Soda',
    description: 'Chilled sparkling club soda with freshly squeezed green lime juice, roasted cumin powder, and mint leaves (Sweet & Salt).',
    price: 59,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },

  // 4. The Royal Table (Whitefield)
  {
    restaurantIndex: 3,
    categoryName: 'North Indian & Mughlai',
    name: 'Paneer Butter Masala',
    description: 'Fresh malai paneer cubes simmered in a luscious velvet gravy of ripe tomatoes, butter, cashew cream, and dried fenugreek.',
    price: 219,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 3,
    categoryName: 'North Indian & Mughlai',
    name: 'Butter Naan',
    description: 'Traditional leavened flatbread baked in tandoor oven until blistered and brushed liberally with fresh cultured butter.',
    price: 49,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 3,
    categoryName: 'Tandoor & Starters',
    name: 'Paneer Tikka',
    description: 'Smoky cottage cheese cubes, bell peppers, and sweet onions skewered and roasted with ajwain and mustard marinade.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 3,
    categoryName: 'Desserts & Sweets',
    name: 'Gulab Jamun',
    description: 'Two warm, soft milk mawa dumplings soaked in cardamom and saffron-infused sugar syrup.',
    price: 89,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 3,
    categoryName: 'Desserts & Sweets',
    name: 'Rasmalai',
    description: 'Two delicate spongy cottage cheese discs steeped in thickened saffron-pistachio rabri milk with rose petals.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },

  // 5. South Street Kitchen (Jayanagar)
  {
    restaurantIndex: 4,
    categoryName: 'South Indian',
    name: 'Mysore Masala Dosa',
    description: 'Crisp benne dosa coated inside with fiery Mysore garlic-red chili chutney, stuffed with spiced potato and onion bhaji.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 4,
    categoryName: 'Street Food & Chaat',
    name: 'Samosa',
    description: 'Pair of flaky golden pastry pyramids packed with spiced green peas and potatoes, served with tamarind and mint chutneys.',
    price: 49,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 4,
    categoryName: 'Filter Coffee & Beverages',
    name: 'Masala Chai',
    description: 'Fragrant Assam black tea slow-simmered with crushed ginger, green cardamom, cloves, and whole milk.',
    price: 49,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    restaurantIndex: 4,
    categoryName: 'South Indian',
    name: 'Ghee Podi Idli',
    description: 'Steamed button idlis tossed generously in fragrant Gunpowder podi and hot melted desi ghee.',
    price: 89,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
  },
];
